// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly vizNote: string;
  readonly vizPlaceholder: string;
  readonly vizTitle: string;
};
export default styles;
