// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly bands: string;
  readonly control: string;
  readonly crumb: string;
  readonly crumbX: string;
  readonly crumbs: string;
  readonly isDetail: string;
  readonly pageName: string;
  readonly summary: string;
  readonly summaryControl: string;
  readonly toolbar: string;
};
export default styles;
