// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly back: string;
  readonly branch: string;
  readonly branchHead: string;
  readonly branchYield: string;
  readonly branches: string;
  readonly control: string;
  readonly crumb: string;
  readonly crumbModel: string;
  readonly crumbSep: string;
  readonly crumbX: string;
  readonly crumbs: string;
  readonly dim: string;
  readonly hideMinor: string;
  readonly isCollapsed: string;
  readonly isDetail: string;
  readonly keep: string;
  readonly path: string;
  readonly pathToggle: string;
  readonly summary: string;
  readonly summaryControl: string;
  readonly toolbar: string;
};
export default styles;
