// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly summaryControl: string;
  readonly toolbar: string;
};
export default styles;
