// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly isDim: string;
  readonly isLowConfidence: string;
  readonly isSelected: string;
  readonly scatterContainer: string;
  readonly scatterHull: string;
  readonly scatterHullLabel: string;
  readonly scatterHullPath: string;
  readonly scatterHullRing: string;
  readonly scatterPoint: string;
  readonly scatterSvg: string;
};
export default styles;
