// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly band: string;
  readonly bandYield: string;
  readonly bands: string;
};
export default styles;
