// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly anchor: string;
  readonly dropdown: string;
  readonly dropdownLabel: string;
  readonly isOpen: string;
  readonly menu: string;
  readonly pills: string;
  readonly row: string;
  readonly rowLabel: string;
  readonly toggle: string;
};
export default styles;
