// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly isSelected: string;
  readonly pill: string;
  readonly pillGroupLoose: string;
};
export default styles;
