// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly bad: string;
  readonly good: string;
  readonly pill: string;
  readonly warn: string;
};
export default styles;
