// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly caveatBadge: string;
  readonly isActive: string;
  readonly isLow: string;
  readonly isModerate: string;
  readonly loadError: string;
  readonly plotWell: string;
  readonly viewCaption: string;
  readonly viewHint: string;
  readonly viewTab: string;
  readonly viewTabs: string;
  readonly vizBody: string;
  readonly vizHead: string;
  readonly vizName: string;
  readonly vizPanel: string;
  readonly vizState: string;
  readonly vizSubject: string;
};
export default styles;
