// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly alluvialContainer: string;
  readonly alluvialLabel: string;
  readonly alluvialLabelSource: string;
  readonly alluvialLabelTarget: string;
  readonly alluvialNode: string;
  readonly alluvialRibbon: string;
  readonly alluvialSvg: string;
  readonly isDim: string;
  readonly isSelected: string;
};
export default styles;
