// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly heatmapContainer: string;
  readonly heatmapLegend: string;
  readonly heatmapLegendBar: string;
  readonly heatmapLegendLabel: string;
  readonly heatmapTooltip: string;
  readonly ttScore: string;
};
export default styles;
