// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly block: string;
  readonly body: string;
  readonly category: string;
  readonly citationLink: string;
  readonly colophon: string;
  readonly container: string;
  readonly count: string;
  readonly entries: string;
  readonly entry: string;
  readonly filter: string;
  readonly group: string;
  readonly head: string;
  readonly isOn: string;
  readonly kind: string;
  readonly layout: string;
  readonly run: string;
  readonly runHead: string;
  readonly selector: string;
  readonly state: string;
  readonly sub: string;
  readonly subject: string;
  readonly subjectName: string;
  readonly subjectState: string;
  readonly workTitle: string;
  readonly year: string;
};
export default styles;
