import { baseFeatureId } from "../../../shared/lib/corpus";

//: Mirrors pipeline/cluster_methods.py's lexical-vs-syntactic split, not featureNames.ts's.
const THEMATIC_CLUSTER_SIGNALS = new Set([
  "lexical",
  "root",
  "named-entity-identity",
  "lexical-set",
  "named-entity",
  "alephbert-mean-pool",
  "alephbert-soft-alignment",
  "alephbert-soft-alignment-top-pc",
  "alephbert-soft-alignment-whitened",
  "neodictabert-soft-alignment",
  "berel-mean-pool",
  "berel-soft-alignment",
  "berel-soft-alignment-top-pc",
  "berel-soft-alignment-whitened",
  "neodictabert-soft-alignment-top-pc",
  "neodictabert-soft-alignment-whitened",
  "bge-multilingual-gemma2-mean-pool",
  "bge-multilingual-gemma2-mean-pool-unvocalized",
  "bge-multilingual-gemma2-soft-alignment",
  "bge-multilingual-gemma2-soft-alignment-unvocalized",
  "qwen3-embedding-mean-pool",
  "qwen3-embedding-mean-pool-unvocalized",
  "qwen3-embedding-soft-alignment",
  "qwen3-embedding-soft-alignment-unvocalized",
  "kalm-embedding-mean-pool",
  "kalm-embedding-mean-pool-unvocalized",
  "kalm-embedding-soft-alignment",
  "kalm-embedding-soft-alignment-unvocalized",
  "gemini-mean-pool",
  "gemini-mean-pool-unvocalized",
  "gemini-soft-alignment",
  "gemini-soft-alignment-unvocalized",
  "openai-mean-pool",
  "openai-mean-pool-unvocalized",
  "openai-soft-alignment",
  "openai-soft-alignment-unvocalized",
  "cohere-mean-pool",
  "cohere-mean-pool-unvocalized",
  "cohere-soft-alignment",
  "cohere-soft-alignment-unvocalized",
  "voyage-mean-pool",
  "voyage-mean-pool-unvocalized",
  "voyage-soft-alignment",
  "voyage-soft-alignment-unvocalized",
  "bge-m3-mean-pool",
  "bge-m3-mean-pool-unvocalized",
  "bge-m3-soft-alignment",
  "bge-m3-soft-alignment-unvocalized",
  "gte-multilingual-base-soft-alignment-unvocalized",
  "me5-large-instruct-mean-pool",
  "me5-large-instruct-mean-pool-unvocalized",
  "me5-large-instruct-soft-alignment",
  "me5-large-instruct-soft-alignment-unvocalized",
]);

/** Whether a method clusters on vocabulary rather than on grammatical form. */
export function isThematicClustering(clusterMethodId: string): boolean {
  return THEMATIC_CLUSTER_SIGNALS.has(baseFeatureId(clusterMethodId));
}
