// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly detailEmpty: string;
  readonly detailHeader: string;
  readonly detailIncipit: string;
  readonly detailNumber: string;
  readonly detailPanel: string;
  readonly detailStats: string;
  readonly similarHeading: string;
  readonly similarItem: string;
  readonly similarItemBarFill: string;
  readonly similarItemBarTrack: string;
  readonly similarItemIncipit: string;
  readonly similarItemPsalm: string;
  readonly similarItemScore: string;
  readonly similarItemTop: string;
  readonly similarList: string;
};
export default styles;
