// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly figure: string;
  readonly figureTooltip: string;
  readonly square: string;
  readonly tableScale: string;
};
export default styles;
