// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly card: string;
  readonly cardBlurb: string;
  readonly cardName: string;
  readonly cardWhat: string;
  readonly cards: string;
  readonly figurePending: string;
  readonly home: string;
  readonly isCluster: string;
  readonly isCompare: string;
};
export default styles;
