// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly edgeCount: string;
  readonly isDim: string;
  readonly isSelected: string;
  readonly networkContainer: string;
  readonly networkControls: string;
  readonly networkEdge: string;
  readonly networkLabel: string;
  readonly networkNode: string;
  readonly thresholdValue: string;
};
export default styles;
