// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly edgeCount: string;
  readonly networkControls: string;
  readonly networkMount: string;
  readonly thresholdValue: string;
};
export default styles;
