// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly appHeader: string;
  readonly brand: string;
  readonly brandMark: string;
  readonly footerSep: string;
  readonly layout: string;
  readonly methodPicker: string;
  readonly page: string;
  readonly pageNav: string;
  readonly panel: string;
  readonly siteFooter: string;
  readonly subtitle: string;
  readonly titleBlock: string;
  readonly titleName: string;
  readonly titleScope: string;
};
export default styles;
