// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly bookLegend: string;
  readonly isSelected: string;
  readonly legendSwatch: string;
  readonly pickerHeader: string;
  readonly pickerPanel: string;
  readonly psalmCell: string;
  readonly psalmGrid: string;
};
export default styles;
