// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly isActive: string;
  readonly isOpen: string;
  readonly representationChip: string;
  readonly representationOptions: string;
  readonly representationPanel: string;
  readonly representationRow: string;
  readonly representationRowLabel: string;
  readonly representationSelect: string;
  readonly representationToggle: string;
  readonly representationTypeChip: string;
};
export default styles;
