// Generated by scripts/css-module-types.mjs. Run `npm run styles:types` after editing the stylesheet.
declare const styles: {
  readonly alignmentClusterGenre: string;
  readonly alignmentClusterHeader: string;
  readonly alignmentClusterNumber: string;
  readonly alignmentCorner: string;
  readonly alignmentDetail: string;
  readonly alignmentGenreName: string;
  readonly alignmentGenreTotal: string;
  readonly alignmentLegend: string;
  readonly alignmentLegendBar: string;
  readonly alignmentLegendShade: string;
  readonly alignmentRowHeader: string;
  readonly alignmentStatLabel: string;
  readonly alignmentStatTile: string;
  readonly alignmentStatTiles: string;
  readonly alignmentStatValue: string;
  readonly alignmentTable: string;
  readonly isDark: string;
  readonly isSelectedCell: string;
  readonly tableScroll: string;
};
export default styles;
